name: gatographql-extensions-for-prod
recipe: wordpress
config:
  webroot: wordpress
  php: '7.2'
  ssl: true
proxy:
  mailhog:
    - mail.gatographql-extensions-for-prod.lndo.site
services:
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
  appserver:
    scanner:
      retry: 10
      okCodes:
        - 200
        - 301
        - 302
  database:
    portforward: true
env_file:
  - defaults.local.env
