name: gatographql-extensions-for-prod
recipe: wordpress
config:
  webroot: wordpress
  php: '7.2'
  ssl: true
proxy:
  mailhog:
    - mail.gatographql-extensions-for-prod.lndo.site
services:
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
  appserver:
    scanner:
      retry: 10
      okCodes:
        - 200
        - 301
        - 302
    overrides:
      volumes:
        - ../../submodules/GatoGraphQL/webservers/_shared:/app/_shared-webserver
        - ../../submodules/GatoGraphQL/webservers/_shared-prod:/app/_shared-webserver-prod
  database:
    portforward: true
env_file:
  - defaults.env
  - defaults.local.env
