name: gatographql-extensions
recipe: wordpress
proxy:
  mailhog:
    - mail.gatographql-extensions.lndo.site
config:
  webroot: wordpress
  php: '8.2'
  ssl: true
  database: mariadb
  xdebug: true
  config:
    php: ../../submodules/GatoGraphQL/webservers/shared/config/php.ini
services:
  database:
    portforward: true
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
  appserver:
    scanner:
      retry: 10
      okCodes:
        - 200
        - 301
        - 302
    overrides:
      environment:
        XDEBUG_MODE: ''
      volumes:
        - ../../submodules/GatoGraphQL/webservers/_shared:/app/_shared-webserver
env_file:
  - ../../submodules/GatoGraphQL/webservers/gatographql/defaults.app.env
  - defaults.env
  - defaults.local.env
