#!/bin/sh
wp config set AUTH_KEY          '*qCDwXB=ED1|0_V!B~U8|J [%T~)KFPQ2q)W`zf?s,j;:l**qBI0cuQ[UFJN;-N['
wp config set SECURE_AUTH_KEY   '9dxzixY%^d`@D^Ad$f|$/N=)HZ{+-2n33Rz1(+/OLp5pRYjf-G~W0@gjcol9qS[7'
wp config set LOGGED_IN_KEY     'mj/-Wwz*fZ+8=?TT=#BC-s=w}!PPt*i{%S8T/a9[CZry!)l)h~S,z:.*-^ {,>@o'
wp config set NONCE_KEY         ')abGM4S-eING<w&1.%F`ci|7B;E:[*Ne8S9m&SK;fy=xD7SxbYkjo~uG07k^=o2#'
wp config set AUTH_SALT         'Q|FO!e)b[@(6J)7K1wQ{*%sIfw/PNkM{r@#D)Ky (VQYn)b$=ZQL9[U5A|%_[l{)'
wp config set SECURE_AUTH_SALT  'c%|(=J_n/8B_oy_Oj];XoltWckE6~C_lGdhXk8fXgwpl=t,aZ4*Lv5v!gs^+yL;R'
wp config set LOGGED_IN_SALT    '<6U/=/b1iMDWZT/X{~()d0LGB|dr(_;E|<Dpp5Onip(-WsJjKij]-4a@<bd_a2T='
wp config set NONCE_SALT        '-ZaM>=QG,?La+-Xu7o(B/i4)l^-*{Z8}Opb1#~AUvZ=Gxy(O[x_RzkXh2f1R%+HC'
wp config set WP_CACHE_KEY_SALT '2$z+KQ]`i3kb[ME#g^Sq2ZU2[9 S;QIwTI%qfw$c)jt08y%1!x4yq3Gr+y3-y9+V'
